@startuml Observable订阅时序图


actor user



user -> ObservableCreate : subscribe
ObservableCreate ->  RxJavaPlugins : onSubscribe
ObservableCreate -> ObservableCreate : subscribeActual

create CreateEmitter
ObservableCreate -> CreateEmitter : new
ObservableCreate -> Observer : onSubscribe
ObservableCreate -> ObservableOnSubscribe : subscribe




' user -> Observable : create
' Observable -> RxJavaPlugins : onAssembly
' RxJavaPlugins -> user : ObservableCreate
@enduml